# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# xcversion(version: "13.3.1")
# xcode_select "/Applications/Xcode-13.3.1.app"


default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Description of what the lane does"


  lane :testandbuild do
    match(type:  "adhoc", readonly: is_ci, force_for_new_devices: true,
    app_identifier: "com.RNLogin.app.RNLogin")
    gym(export_method: "ad-hoc", scheme: "RNLogin")
  end
 
end
